server:
  port: 8080

spring:
  application:
    name: home-test

  datasource:
    url: jdbc:postgresql://3.1.200.103:5432/mydatabase
    username: myuser
    password: mypassword123
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  data:
    redis:
      host: 3.1.200.103
      port: 6379
      password: newpass123
      timeout: 5s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 1s
