server:
  port: 8080

spring:
  application:
    name: home-test

  datasource:
    url: jdbc:postgresql://{host}:{port}/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  data:
    redis:
      host: host
      port: port
      password: pass
      timeout: 5s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 1s
